# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI for .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI Verify
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet_version: 9.0.x
